#!/bin/sh


#python lcocommissioning/sbig/get_sbig_frame.py --bias  --expcnt 5 --binning 1
cycles="50 100 150 200 250"

for ii in $cycles
do
   python lcocommissioning/sbig/get_sbig_frame.py --flat --exptime 10 --ledvoltage 3.0   --binning 1 --expcnt 2 --nburstcycles $ii
done




